#-Basic info----------------------------------------------------------------------------------------
name: ariba_virulencefinder
version: 2.0
#---------------------------------------------------------------------------------------------------

#-Details-------------------------------------------------------------------------------------------
details:
  category: virulence
  schema_version: 2.0
  target: sample
  type: pipeline
  recommendation: recommended
  description: >
    This preforms read based mapping against the virulencefinder DB's. The options show the species entries 
    which will be attempted for mlst with key originating from the species DB. This is done against 
    the cge_db using ariba.
#---------------------------------------------------------------------------------------------------

#-Docker location-----------------------------------------------------------------------------------
dockerfile: &dockerfile "docker://ssidk/bifrost-ariba_virulencefinder:2.0"
#---------------------------------------------------------------------------------------------------

#-Options-------------------------------------------------------------------------------------------
options:
#---------------------------------------------------------------------------------------------------

#-Required resource files---------------------------------------------------------------------------
resources:
  database_path: "/bifrost_resources/virulencefinder/ref_db/"
#---------------------------------------------------------------------------------------------------

#-Requirements to run component---------------------------------------------------------------------
requirements:
  sample:
    properties:
      datafiles:
        paired_reads:
      species_detection:
        summary:
          species: 
            - "Escherichia coli"
            - "Staphylococcus aureus"
            - "Listeria monocytogenes"
            - "Enterococcus faecium"
#---------------------------------------------------------------------------------------------------

#-DB Value changes (excluding component output)-----------------------------------------------------
db_values_changes:
  files:
    - "ariba_virulencefinder/virulence/report.tsv"
  sample:
    properties:
      virulence:
        summary: 
        component:
          _id: 
          date: "ObjectId"
    report:
      virulence:
        title: Virulence
        info: *dockerfile
        columns:  # headers, these values are statically present in datadump
          - {id: "gene", name: "gene"}
          - {id: "coverage", name: "%cov"}
          - {id: "identity", name: "%id"}
          - {id: "variants", name: "# of variants"}
        data: []  # list of dicts parsed in datadump
  sample_component:
    summary:
    results:
      ariba_virulencefinder/virulence/report.tsv: {}
#---------------------------------------------------------------------------------------------------
