version: '3.8'
services:
  python:
    build:
      context: .
      args:
        BUILD_ENV: dev
    env_file:
      - .secrets/mongodb_dev_key.env
  python-tests:
    build:
      context: .
      args:
        BUILD_ENV: dev
    env_file:
      - .secrets/mongodb_dev_key.env
    working_dir: /bifrost_ariba_virulencefinder/
    volumes:
      - ./bifrost_ariba_virulencefinder:/bifrost_ariba_virulencefinder/bifrost_ariba_virulencefinder
      - ./tests:/bifrost_ariba_virulencefinder/tests
      - ../../lib/bifrostlib:/bifrostlib
      # - ../bifrost_run_launcher/bifrost_run_launcher:/bifrost_run_launcher/bifrost_run_launcher
    entrypoint: watchmedo auto-restart --recursive --pattern="*.py" --directory="/bifrost_ariba_virulencefinder" -- pytest --verbose --ignore=resources
    depends_on:
      - python