#-Basic info----------------------------------------------------------------------------------------
display_name: ariba_virulencefinder
name: &name ariba_virulencefinder__2.1.1__201116
version:
  schema: 2.0
  code: 2.1.1
  resource: 201116
#---------------------------------------------------------------------------------------------------

#-Details-------------------------------------------------------------------------------------------
details:
  target: sample
  description: >
    This preforms read based mapping against the virulencefinder DB's. The options show the species entries 
    which will be attempted for mlst with key originating from the species DB. This is done against 
    the cge_db using ariba.
#---------------------------------------------------------------------------------------------------

#-Category info-------------------------------------------------------------------------------------
category: [virulence]
#---------------------------------------------------------------------------------------------------

#-Install-------------------------------------------------------------------------------------------
install:
  path: # Set by install program
  dockerfile: docker://ssidk/bifrost_ariba_virulencefinder
#---------------------------------------------------------------------------------------------------

#-Options-------------------------------------------------------------------------------------------
options:
#---------------------------------------------------------------------------------------------------

#-Required resource files---------------------------------------------------------------------------
resources:
  database_path: "/bifrost_ariba_virulencefinder/resources/virulencefinder/ref_db/"
#---------------------------------------------------------------------------------------------------

#-Requirements to run component---------------------------------------------------------------------
requirements:
  sample:
    properties:
      paired_reads:
        summary:
          data:
      species_detection:
        summary:
          species: 
            - "Escherichia coli"
            - "Staphylococcus aureus"
            - "Listeria monocytogenes"
            - "Enterococcus faecium"
#---------------------------------------------------------------------------------------------------

#-DB Value changes (excluding component output)-----------------------------------------------------
db_values_changes:
  files:
    - "ariba_virulencefinder/virulence/report.tsv"
  sample:
    properties:
      virulence:
        summary: 
        component:
          _id: 
          date: "ObjectId"
    report:
      virulence:
        title: Virulence
        info: *name
        columns:  # headers, these values are statically present in datadump
          - {id: "gene", name: "gene"}
          - {id: "coverage", name: "%cov"}
          - {id: "identity", name: "%id"}
          - {id: "variants", name: "# of variants"}
        data: []  # list of dicts parsed in datadump
  sample_component:
    summary:
    results:
      ariba_virulencefinder/virulence/report.tsv: {}
#---------------------------------------------------------------------------------------------------
